import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from "react-bootstrap";
import AppHeader from "./components/app.header";
import AppFooter from "./components/app.footer";
import AppTable from "./components/app.table";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
      <AppHeader/>
        <Container>
        {children}
        </Container>
        <AppTable/>
        <AppFooter/>
        </body>
        <div>the end</div>
    </html>
  );
}
